name: Verivinex Production Build

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: mastermindcms/build:latest
      volumes:
        - ${{ github.WORKSPACE }}:/app
    steps:
      - name: Check out a repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Production Build
        run: npm run build
      - name: Copy to Production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build/*"
          target: "/var/cloud/verivinex.com/www/app"
          strip_components: 1
